<script setup lang="ts">
import { FileText, FolderTree, Image, LogOut, Menu, Tags, UserRound, X } from 'lucide-vue-next'
import { shallowRef } from 'vue'
import { useRouter } from 'vue-router'
import { useAuth } from '@/composables/useAuth'
const menuOpen = shallowRef(false)
const router = useRouter()
const { signOut } = useAuth()
const links = [{ label:'文章', to:'/', icon:FileText },{ label:'分类', to:'/categories', icon:FolderTree },{ label:'标签', to:'/tags', icon:Tags },{ label:'媒体', to:'/media', icon:Image },{ label:'账户', to:'/account', icon:UserRound }]
async function logout(){ await signOut(); await router.push({ name:'login' }) }
</script>
<template><div class="admin-shell"><aside class="sidebar" :class="{ 'sidebar--open': menuOpen }"><RouterLink class="brand" to="/" @click="menuOpen=false">Chen Blog<span>CMS</span></RouterLink><nav><RouterLink v-for="link in links" :key="link.to" :to="link.to" class="nav-link" @click="menuOpen=false"><component :is="link.icon" :size="18" />{{ link.label }}</RouterLink></nav><button class="logout" type="button" @click="logout"><LogOut :size="17" />退出登录</button></aside><div class="workspace"><header class="topbar"><button class="mobile-menu" type="button" :aria-label="menuOpen ? '关闭菜单' : '打开菜单'" @click="menuOpen=!menuOpen"><X v-if="menuOpen" :size="19"/><Menu v-else :size="19"/></button><span class="topbar__title">内容管理</span><ThemeToggle /></header><main class="workspace__main"><slot /></main></div></div></template>
<style scoped>.admin-shell{display:grid;min-height:100svh;grid-template-columns:14.5rem minmax(0,1fr)}.sidebar{display:flex;position:sticky;top:0;height:100svh;flex-direction:column;padding:1.2rem;border-right:1px solid var(--border);background:var(--bg-soft)}.brand{margin:.2rem .35rem 2rem;font-weight:800;letter-spacing:-.04em}.brand span{margin-left:.4rem;color:var(--accent);font-size:.7rem;letter-spacing:.09em}.sidebar nav{display:grid;gap:.25rem}.nav-link,.logout{display:flex;align-items:center;gap:.65rem;padding:.65rem .7rem;border:0;border-radius:.45rem;background:transparent;color:var(--text-muted);font-size:.9rem;text-align:left}.nav-link:hover,.nav-link.router-link-active{background:var(--accent-soft);color:var(--accent);font-weight:700}.logout{margin-top:auto}.logout:hover{color:var(--danger)}.workspace{min-width:0}.topbar{display:flex;min-height:4rem;align-items:center;justify-content:space-between;padding:0 1.5rem;border-bottom:1px solid var(--border);background:color-mix(in srgb,var(--bg) 90%,transparent);backdrop-filter:blur(10px)}.topbar__title{font-size:.86rem;color:var(--text-muted);font-weight:700}.workspace__main{width:min(100% - 3rem,78rem);margin:0 auto;padding:2.5rem 0}.mobile-menu{display:none;border:0;background:transparent;color:var(--text)}@media(max-width:760px){.admin-shell{grid-template-columns:1fr}.sidebar{position:fixed;z-index:10;width:16rem;transform:translateX(-101%);transition:transform 160ms ease}.sidebar--open{transform:translateX(0);box-shadow:1rem 0 2rem color-mix(in srgb,var(--text) 15%,transparent)}.mobile-menu{display:grid}.workspace__main{width:min(100% - 2rem,78rem);padding:1.75rem 0}}</style>
