<script setup lang="ts">
import { computed, reactive, shallowRef } from 'vue'
import { renderMarkdown } from '@chen-blog/markdown'
import type { PostDraftInput } from '@chen-blog/shared-types'
import { toSlug } from '@chen-blog/shared-utils'
import type { AdminPost, AdminMedia, TaxonomyItem } from '@/features/content/api'
const { post, categories, tags, media, saving = false } = defineProps<{post:AdminPost|null;categories:TaxonomyItem[];tags:TaxonomyItem[];media:AdminMedia[];saving?:boolean}>()
const emit=defineEmits<{save:[input:PostDraftInput]}>()
const model=reactive<PostDraftInput>({title:post?.title??'',slug:post?.slug??'',summary:post?.summary??'',content:post?.content??'',categoryId:post?.category_id??null,coverMediaId:post?.cover_media_id??null,tagIds:post?.post_tags.map(item=>item.tag_id)??[],status:post?.status==='archived'?'archived':'draft'})
const preview=computed(()=>renderMarkdown(model.content));const slugEdited=shallowRef(Boolean(post?.slug))
function suggestSlug(){if(!slugEdited.value)model.slug=toSlug(model.title)} function submit(){emit('save',{...model,tagIds:[...model.tagIds]})}
</script>
<template><form class="editor-form" @submit.prevent="submit"><section class="editor-main"><div class="field"><label for="title">标题</label><input id="title" v-model="model.title" class="input title-input" required @input="suggestSlug"></div><div class="field"><label for="slug">Slug</label><input id="slug" v-model="model.slug" class="input" required @input="slugEdited=true"><span class="hint">发布地址会使用它；发布后如需修改，请先转回草稿。</span></div><div class="field"><label for="summary">摘要</label><textarea id="summary" v-model="model.summary" class="textarea summary-input" maxlength="320"></textarea></div><div class="field"><label for="content">Markdown 正文</label><textarea id="content" v-model="model.content" class="textarea editor-content" required></textarea></div><details class="preview"><summary>预览</summary><article class="preview__content" v-html="preview" /></details></section><aside class="editor-side"><div class="field"><label for="status">保存状态</label><select id="status" v-model="model.status" class="select"><option value="draft">草稿</option><option value="archived">归档</option></select></div><div class="field"><label for="category">分类</label><select id="category" v-model="model.categoryId" class="select"><option :value="null">未分类</option><option v-for="category in categories" :key="category.id" :value="category.id">{{category.name}}</option></select></div><fieldset class="tag-field"><legend>标签</legend><label v-for="tag in tags" :key="tag.id"><input v-model="model.tagIds" type="checkbox" :value="tag.id"> {{tag.name}}</label></fieldset><div class="field"><label for="cover">封面媒体</label><select id="cover" v-model="model.coverMediaId" class="select"><option :value="null">不使用封面</option><option v-for="item in media" :key="item.id" :value="item.id">{{item.alt_text||item.object_path}}</option></select></div><button class="button button--primary" :disabled="saving" type="submit">{{saving?'正在保存…':'保存草稿'}}</button></aside></form></template>
<style scoped>.editor-form{display:grid;grid-template-columns:minmax(0,1fr) 16rem;gap:2rem;align-items:start}.editor-main{display:grid;gap:1.15rem}.title-input{font-size:1.35rem;font-weight:700;letter-spacing:-.03em}.summary-input{min-height:6rem}.editor-content{min-height:32rem;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.9rem}.editor-side{position:sticky;top:5rem;display:grid;gap:1rem;padding:1rem;border:1px solid var(--border);border-radius:.65rem;background:var(--bg-soft)}.tag-field{display:grid;gap:.45rem;margin:0;padding:0;border:0}.tag-field legend{margin-bottom:.3rem;font-size:.85rem;font-weight:700}.tag-field label{font-size:.86rem}.preview{border-top:1px solid var(--border);padding-top:1rem}.preview summary{cursor:pointer;font-weight:700}.preview__content{margin-top:1rem;color:var(--text-muted);line-height:1.8}.preview__content :deep(pre){overflow:auto;padding:1rem;background:var(--bg-soft)}@media(max-width:900px){.editor-form{grid-template-columns:1fr}.editor-side{position:static;grid-template-columns:repeat(2,minmax(0,1fr))}.editor-side button{grid-column:1/-1}}@media(max-width:560px){.editor-side{grid-template-columns:1fr}}</style>
