<script setup lang="ts">
import { Upload } from 'lucide-vue-next'
import { onMounted, shallowRef } from 'vue'
import AdminShell from '@/components/AdminShell.vue'
import { getPublicImageUrl, listMedia, uploadMedia, type AdminMedia } from '@/features/content/api'
const media=shallowRef<AdminMedia[]>([]),file=shallowRef<File|null>(null),altText=shallowRef(''),uploading=shallowRef(false),message=shallowRef('')
async function refresh(){media.value=await listMedia()}onMounted(()=>void refresh())
async function upload(){if(!file.value)return;uploading.value=true;message.value='';try{await uploadMedia(file.value,altText.value);file.value=null;altText.value='';message.value='图片已上传。公开 bucket 中的文件会立即可访问。';await refresh()}catch(error){message.value=error instanceof Error?error.message:'上传失败。'}finally{uploading.value=false}}
function onFile(event:Event){file.value=(event.target as HTMLInputElement).files?.[0]??null}
</script>
<template><AdminShell><div class="page-head"><div><p class="eyebrow">post-images</p><h1 class="page-title">媒体</h1></div></div><p class="hint">仅可上传图片；V1 不提供物理删除，避免正文 Markdown 出现失效引用。</p><section class="upload-panel"><div class="field"><label for="file">图片文件</label><input id="file" accept="image/jpeg,image/png,image/webp,image/gif" type="file" @change="onFile"></div><div class="field"><label for="alt">替代文本</label><input id="alt" v-model="altText" class="input" placeholder="描述图片内容"></div><button class="button button--primary" :disabled="!file||uploading" type="button" @click="upload"><Upload :size="16"/>{{uploading?'正在上传…':'上传图片'}}</button></section><p v-if="message" class="hint">{{message}}</p><div v-if="!media.length" class="empty-state">尚未上传图片。</div><div v-else class="media-grid"><article v-for="item in media" :key="item.id" class="media-item"><img :src="getPublicImageUrl(item)" :alt="item.alt_text"><div><strong>{{item.alt_text||'未填写替代文本'}}</strong><span>{{item.object_path}}</span></div></article></div></AdminShell></template>
<style scoped>.page-head{margin-bottom:1rem}.upload-panel{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr) auto;align-items:end;gap:1rem;margin:1.5rem 0;padding:1rem;border:1px solid var(--border);border-radius:.65rem;background:var(--bg-soft)}.media-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(13rem,1fr));gap:1rem;margin-top:1.5rem}.media-item{overflow:hidden;border:1px solid var(--border);border-radius:.6rem;background:var(--bg-elevated)}.media-item img{display:block;width:100%;aspect-ratio:4/3;object-fit:cover;background:var(--bg-soft)}.media-item div{display:grid;gap:.2rem;padding:.7rem}.media-item strong,.media-item span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.media-item strong{font-size:.85rem}.media-item span{color:var(--text-muted);font-size:.75rem}@media(max-width:720px){.upload-panel{grid-template-columns:1fr}.upload-panel button{justify-self:start}}</style>
