<script setup lang="ts">
import { Pencil, Plus, Trash2 } from 'lucide-vue-next'
import { computed, onMounted, reactive, shallowRef } from 'vue'
import AdminShell from '@/components/AdminShell.vue'
import { deleteTaxonomy, listTaxonomy, saveTaxonomy, type TaxonomyItem } from '@/features/content/api'
const {kind}=defineProps<{kind:'categories'|'tags'}>();const items=shallowRef<TaxonomyItem[]>([]),editing=shallowRef<TaxonomyItem|null>(null),message=shallowRef('');const form=reactive({name:'',slug:'',description:''});const title=computed(()=>kind==='categories'?'分类':'标签')
async function refresh(){items.value=await listTaxonomy(kind)}onMounted(()=>void refresh())
function edit(item?:TaxonomyItem){editing.value=item??null;form.name=item?.name??'';form.slug=item?.slug??'';form.description=item?.description??''}async function submit(){try{await saveTaxonomy(kind,{id:editing.value?.id,name:form.name,slug:form.slug,description:form.description});message.value='已保存。';edit();await refresh()}catch(error){message.value=error instanceof Error?error.message:'保存失败。'}}async function remove(id:string){if(!confirm(`确认删除此${title.value}吗？`))return;await deleteTaxonomy(kind,id);await refresh()}
</script>
<template><AdminShell><div class="page-head"><div><p class="eyebrow">taxonomy</p><h1 class="page-title">{{title}}</h1></div><button class="button" type="button" @click="edit()"><Plus :size="16"/>新建{{title}}</button></div><p v-if="message" class="hint">{{message}}</p><section class="taxonomy-layout"><div class="list"><article v-for="item in items" :key="item.id" class="item"><div><strong>{{item.name}}</strong><span>/{{item.slug}}</span><p v-if="kind==='categories'">{{item.description}}</p></div><div><button class="plain-button" title="编辑" @click="edit(item)"><Pencil :size="16"/></button><button class="plain-button danger" title="删除" @click="remove(item.id)"><Trash2 :size="16"/></button></div></article><p v-if="!items.length" class="empty-state">尚无{{title}}。</p></div><form class="form" @submit.prevent="submit"><h2>{{editing?'编辑':'新建'}}{{title}}</h2><div class="field"><label>名称</label><input v-model="form.name" class="input" required></div><div class="field"><label>Slug</label><input v-model="form.slug" class="input" required></div><div v-if="kind==='categories'" class="field"><label>说明</label><textarea v-model="form.description" class="textarea"></textarea></div><button class="button button--primary" type="submit">保存</button></form></section></AdminShell></template>
<style scoped>.page-head{display:flex;align-items:end;justify-content:space-between;margin-bottom:1.5rem}.taxonomy-layout{display:grid;grid-template-columns:minmax(0,1fr) 20rem;gap:2rem}.list{border-top:1px solid var(--border)}.item{display:flex;align-items:start;justify-content:space-between;gap:1rem;padding:1rem 0;border-bottom:1px solid var(--border)}.item strong{margin-right:.5rem}.item span,.item p{color:var(--text-muted);font-size:.84rem}.item p{margin:.3rem 0 0}.plain-button{padding:.35rem;border:0;background:transparent;color:var(--text-muted)}.plain-button:hover{color:var(--accent)}.plain-button.danger:hover{color:var(--danger)}.form{display:grid;align-content:start;gap:1rem;padding:1rem;border:1px solid var(--border);border-radius:.65rem;background:var(--bg-soft)}.form h2{margin:0;font-size:1.1rem}@media(max-width:760px){.taxonomy-layout{grid-template-columns:1fr}}</style>
