import type { PostDraftInput, PostStatus } from '@chen-blog/shared-types'
import { getSupabase } from '@/lib/supabase'

export type AdminPost = { id:string; title:string; slug:string; summary:string; content:string; status:PostStatus; category_id:string|null; cover_media_id:string|null; published_at:string|null; updated_at:string; deleted_at:string|null; post_tags:{ tag_id:string }[] }
export type TaxonomyItem = { id:string; name:string; slug:string; description?:string }
export type AdminMedia = { id:string; bucket_id:string; object_path:string; alt_text:string; created_at:string }

export async function listPosts(){ const {data,error}=await getSupabase().from('posts').select('id,title,slug,summary,status,updated_at,published_at,deleted_at').order('updated_at',{ascending:false}); if(error) throw error; return data as AdminPost[] }
export async function getPost(id:string){ const {data,error}=await getSupabase().from('posts').select('id,title,slug,summary,content,status,category_id,cover_media_id,published_at,updated_at,deleted_at,post_tags(tag_id)').eq('id',id).maybeSingle(); if(error) throw error; return data as AdminPost|null }
export async function savePost(id:string|undefined,input:PostDraftInput){ const values={title:input.title,slug:input.slug,summary:input.summary,content:input.content,category_id:input.categoryId,cover_media_id:input.coverMediaId,status:input.status}; let postId=id; if(postId){const {error}=await getSupabase().from('posts').update(values).eq('id',postId);if(error)throw error}else{const {data,error}=await getSupabase().from('posts').insert(values).select('id').single();if(error)throw error;postId=data.id}if(!postId)throw new Error('文章 ID 缺失。');const {error:deleteError}=await getSupabase().from('post_tags').delete().eq('post_id',postId);if(deleteError)throw deleteError;if(input.tagIds.length){const {error:tagError}=await getSupabase().from('post_tags').insert(input.tagIds.map(tag_id=>({post_id:postId,tag_id})));if(tagError)throw tagError}return postId }
export async function archivePost(id:string){const {error}=await getSupabase().from('posts').update({status:'archived',deleted_at:new Date().toISOString()}).eq('id',id);if(error)throw error}
export async function publishPost(id:string){const {data:{session}}=await getSupabase().auth.getSession();if(!session)throw new Error('登录已失效。');const base=import.meta.env.VITE_BLOG_URL||'http://localhost:3000';const response=await fetch(`${base}/api/admin/posts/${id}/publish`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'}});if(!response.ok)throw new Error((await response.json().catch(()=>null))?.statusMessage||'发布失败。')}
export async function listTaxonomy(kind:'categories'|'tags'){if(kind==='categories'){const {data,error}=await getSupabase().from('categories').select('id,name,slug,description').order('name');if(error)throw error;return data as unknown as TaxonomyItem[]}const {data,error}=await getSupabase().from('tags').select('id,name,slug').order('name');if(error)throw error;return data as unknown as TaxonomyItem[]}
export async function saveTaxonomy(kind:'categories'|'tags',item:Partial<TaxonomyItem>){if(kind==='categories'){const values={name:item.name,slug:item.slug,description:item.description??''};const {error}=item.id?await getSupabase().from('categories').update(values).eq('id',item.id):await getSupabase().from('categories').insert(values);if(error)throw error;return}const values={name:item.name,slug:item.slug};const {error}=item.id?await getSupabase().from('tags').update(values).eq('id',item.id):await getSupabase().from('tags').insert(values);if(error)throw error}
export async function deleteTaxonomy(kind:'categories'|'tags',id:string){const {error}=await getSupabase().from(kind).delete().eq('id',id);if(error)throw error}
export async function listMedia(){const {data,error}=await getSupabase().from('media').select('id,bucket_id,object_path,alt_text,created_at').order('created_at',{ascending:false});if(error)throw error;return data as AdminMedia[]}
export async function uploadMedia(file:File,altText:string){const extension=file.name.split('.').pop()?.toLowerCase()||'image';const path=`${crypto.randomUUID()}.${extension}`;const {error:uploadError}=await getSupabase().storage.from('post-images').upload(path,file,{upsert:false});if(uploadError)throw uploadError;const {data,error}=await getSupabase().from('media').insert({bucket_id:'post-images',object_path:path,alt_text:altText}).select('id,bucket_id,object_path,alt_text,created_at').single();if(error)throw error;return data as AdminMedia}
export function getPublicImageUrl(media:Pick<AdminMedia,'bucket_id'|'object_path'>){return getSupabase().storage.from(media.bucket_id).getPublicUrl(media.object_path).data.publicUrl}
