/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminNavigation: typeof import('./src/components/layout/AdminNavigation.vue')['default']
    AdminOwnerPanel: typeof import('./src/components/layout/AdminOwnerPanel.vue')['default']
    AdminPage: typeof import('./src/components/common/AdminPage.vue')['default']
    AdminShell: typeof import('./src/components/AdminShell.vue')['default']
    AdminSidebar: typeof import('./src/components/layout/AdminSidebar.vue')['default']
    AdminTopbar: typeof import('./src/components/layout/AdminTopbar.vue')['default']
    AsyncState: typeof import('./src/components/common/AsyncState.vue')['default']
    DataToolbar: typeof import('./src/components/common/DataToolbar.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    MarkdownEditor: typeof import('./src/components/MarkdownEditor.vue')['default']
    MediaPickerDialog: typeof import('./src/components/MediaPickerDialog.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    PaginationBar: typeof import('./src/components/common/PaginationBar.vue')['default']
    PostEditorForm: typeof import('./src/components/PostEditorForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBadge: typeof import('./src/components/common/StatusBadge.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
  }
}
