/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminShell: typeof import('./src/components/AdminShell.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    MarkdownEditor: typeof import('./src/components/MarkdownEditor.vue')['default']
    PostEditorForm: typeof import('./src/components/PostEditorForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
  }
}
